services:
- type: web
  name: django-service
  env: docker
  build:
    dockerfile: Dockerfile
    context: .
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: django-mysql
      property: connectionString

databases:
- name: django-mysql
